### ISSUE TITLE
Growing response size

### ISSUE THREAD

**Issue by Codom** [engaging-computing/rSENSE#2865]
When uploading data, iSENSE will return all of the other data in the project in json. This is a problem because when dealing with projects that will need to use a large amount of data (such as groundwater analysis) there is potential that the response from isense will become unreasonably large.

**Comment by charliemirabile** [comment]
Specifically look at the specifications for the append post method. Its response includes all the data from the dataset with the new data appended which could be arbitrarily large

**Comment by Codom** [comment]
This seems to be a problem with appending to datasets, and not related to dataset creation.

**Comment by Codom** [comment]
Closing because #2872 exists
