### ISSUE TITLE
need method for users to change their email address

### ISSUE THREAD

**Issue by fgmart** [engaging-computing/rSENSE#2908]
Users need to be able to update their email addr in case they are losing access to one.

Maybe if they're logged in, provide some way for them to type in a new address.

Then send them a verification email, and install the new addr when they confirm it?

**Comment by ZacharyMcCann** [comment]
Check if it is possible to change a Gmail sign-in to a different address.

**Comment by Avalderrama04** [comment]
it works changing a gmail sign-in to a different address
